version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
      - ./db/etc/my.conf:/etc/mysql/conf.d/my.conf
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64
  app:
    build:
      context: ./app
    volumes:
      - ../src:/work/backend
    depends_on: 
      - db
      - mailhog  
  web:
    build:
      context: ./web
    ports:
      - 80:80
    volumes:
      - ../src:/work/backend
    depends_on: ["app"]
  mailhog:
    image: mailhog/mailhog
    ports:
        - 8025:8025
        - 1025:1025
